### ISSUE TITLE
9桁入力後に"."を押すと後ろに0が四つつく

### ISSUE THREAD

**Issue by ishizakit** [yota-hada/calculator#1]
1. どの数字でも良いので9回ボタンを押す（9桁入力する）
2. "."ボタンを押す
3. 表示領域を超えて「9桁の数字.0000」と表示される

**Comment by nus3** [comment]
修正しました  
[対応するコミット](https://github.com/yota-hada/calculator/commit/a83c1cd613d0d9e6078d989061990e21d50e6f86)
